App\Domain\Anuncios\Domain\AnuncioDomain\Anuncio:
  fields:
    anuncioComponent:
      length: 140
    anuncioState:
      column: anunciostate
      type: string
    id:
      type: string
  type: entity
