parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): 'DATABASE_URL=mysql://root:@127.0.0.1:3306/components'

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Components:
                is_bundle: false
                type: yml
                dir: "%kernel.project_dir%/src/Domain/Components/Domain/Component/Components"
                prefix: App\Domain\Components\Domain\Component\Components
            Component:
                is_bundle: false
                type: yml
                dir: "%kernel.project_dir%/src/Domain/Components/Domain/Component"
                prefix: App\Domain\Components\Domain\Component
            Embebed:
                is_bundle: false
                type: yml
                dir: "%kernel.project_dir%/src/Domain/Components/Domain/Component/Components/ComponentsVO"
                prefix: App\Domain\Components\Domain\Component\Components\ComponentsVO