<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSR98RQV\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSR98RQV/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSR98RQV.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerSR98RQV\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerSR98RQV\srcProdProjectContainer(array(
    'container.build_hash' => 'SR98RQV',
    'container.build_id' => 'ea1a304d',
    'container.build_time' => 1537511462,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSR98RQV');
