<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\Components\UseCases\CreateAnuncio\CreateComponentHandler' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Domain\\Components\\Domain\\EventPublisher.php';
include_once $this->targetDirs[3].'\\src\\IO\\Events\\DomainEventPublisherRabbitMq.php';
include_once $this->targetDirs[3].'\\src\\Domain\\Components\\UseCases\\CreateAnuncio\\ComponentCreatoror.php';
include_once $this->targetDirs[3].'\\src\\Domain\\Components\\UseCases\\CreateAnuncio\\CreateComponentHandlerer.php';

return $this->privates['App\Domain\Anuncios\UseCases\CreateAnuncio\CreateComponentHandler'] = new \App\Domain\Anuncios\UseCases\CreateAnuncio\CreateComponentHandler(new \App\Domain\Anuncios\UseCases\CreateAnuncio\ComponentCreator(($this->privates['anuncio_repository_doctrine'] ?? $this->load('getAnuncioRepositoryDoctrineService.php')), ($this->privates['components_repository_doctrine'] ?? $this->load('getComponentsRepositoryDoctrineService.php')), new \App\IO\Events\DomainEventPublisherRabbitMq()));
