# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

parameters:

services:

#    app.hello_controller:
#        class: api\controllers\AnuncioController
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
   # App\:
   #     resource: '../src/*'
   #     exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
#    # as action arguments even if you don't extend any base controller class
#    api\controllers\:
#        resource: '../src/Controller/AnuncioController'
#        tags: ['anuncio.controller.post']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
#    api.controller.anuncio:
#         class: AnuncioController
#         arguments:

    service_controller:
        class: App\Controller\AnuncioController
        arguments: ['@request_stack','@service_container']

    App\Domain\Anuncios\UseCases\Create\CreateAnuncioHandler:
        class: App\Domain\Anuncios\UseCases\Create\CreateAnuncioHandler
        arguments: ['@anuncio_creator']
    anuncio_repository_doctrine:
        class: App\Domain\Anuncios\Persistance\AnuncioPersistance
        arguments: ['@Doctrine\ORM\EntityManagerInterface']
    anuncio_creator:
        class: App\Domain\Anuncios\UseCases\Create\AnuncioCreator
