<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\Components\UseCases\CreateComponent\CreateComponentHandler' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Domain\\Components\\UseCases\\CreateComponent\\ComponentCreator.php';
include_once $this->targetDirs[3].'\\src\\Domain\\Components\\UseCases\\CreateComponent\\CreateComponentHandler.php';

$a = ($this->privates['components_repository_doctrine'] ?? $this->load('getComponentsRepositoryDoctrineService.php'));

return $this->privates['App\Domain\Components\UseCases\CreateComponent\CreateComponentHandler'] = new \App\Domain\Components\UseCases\CreateComponent\CreateComponentHandler(new \App\Domain\Components\UseCases\CreateComponent\ComponentCreator($a, $a, new \App\IO\Events\DomainEventPublisherRabbitMq()));
