<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Component.controller' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\dependency-injection\\ContainerAwareInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Bundle\\BundleInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\dependency-injection\\ContainerAwareTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Bundle\\Bundle.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\rest-bundle\\FOSRestBundle.php';
include_once $this->targetDirs[3].'\\src\\IO\\Api\\ApiController;
include_once $this->targetDirs[3].'\\src\\Controller\\ComponentController.php';

return $this->services['Component.controller'] = new \App\Controller\ComponentController(($this->services['tactician.commandbus.default'] ?? $this->load('getTactician_Commandbus_DefaultService.php')), ($this->services['request_stack'] ?? $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));
