<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'event_domain.consumer' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\event-dispatcher\\Event.php';
include_once $this->targetDirs[3].'\\vendor\\php-amqplib\\rabbitmq-bundle\\Event\\AMQPEvent.php';
include_once $this->targetDirs[3].'\\src\\IO\\Events\\Consumer.php';
include_once $this->targetDirs[3].'\\src\\Domain\\Components\\Domain\\EventSubscriber.php';
include_once $this->targetDirs[3].'\\src\\IO\\Events\\ExampleConsumerRabbitImplementation.php';

return $this->privates['event_domain.consumer'] = new \App\IO\Events\ExampleConsumerRabbitImplementation(($this->services['tactician.commandbus.default'] ?? $this->load('getTactician_Commandbus_DefaultService.php')));
