<?php
    /**
     * Created by PhpStorm.
     * User: PTL-JGonzalez
     * Date: 21/09/2018
     * Time: 11:58
     */
    
    namespace App\Domain\Components\Exception;
    
    
    use Exception;
    use LogicException;
    use Throwable;

    class MyException extends LogicException implements MyThrowable
    {
    
    
        public static function handleException(string $class)
        {
           // $this->class=$class;
            //$this->domainException="Los campos introducidos son inválidos";
            ArrayException::addException($class);
           // parent::__construct($this->domainException, 404, null);
            return new parent($class,404,null);
        }
    
         public function __toString() {
           return $this->class; // TODO: Change the autogenerated stub
    }
    }