<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxWxVdP\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxWxVdP/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGxWxVdP.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGxWxVdP\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerGxWxVdP\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'GxWxVdP',
    'container.build_id' => 'c61d8dc5',
    'container.build_time' => 1537367902,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxWxVdP');
